/-
Copyright (c) 2026 ModularPhysics Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ModularPhysics Contributors
-/
import StringGeometry.RiemannSurfaces.GAGA.Bridge.SpectrumConstruction
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.Topology.Irreducible

/-!
# Scheme Properties for Curves from CompactAlgebraicCurve

This file establishes key scheme-theoretic properties for the curve construction
from `CompactAlgebraicCurve`:

1. **Integral**: The function field is a field (no zero divisors)
2. **One-dimensional**: Local rings at closed points are DVRs
3. **Proper**: From regularIsConstant (valuative criterion)
4. **Smooth**: DVRs with residue field ≅ ℂ (regular local rings)

## Main Results

* `curveSpace_irreducible` - The space is irreducible (generic point is dense)
* `genericPoint_dense` - The generic point is dense in the Zariski topology
* `closedPoint_isClosed` - Each closed point is indeed closed
* `valuationSubringAt_isDomain` - The stalk at a closed point is a domain

## References

* Hartshorne "Algebraic Geometry" II.4-6
* Liu "Algebraic Geometry and Arithmetic Curves" Ch 4, 7
-/

namespace RiemannSurfaces.GAGA.Bridge

open TopologicalSpace Algebraic

variable (C : CompactAlgebraicCurve)

/-!
## Topological Properties

The curve space `CurvePoint C` with the Zariski topology has:
- The generic point is in every nonempty open set
- Closed points are closed singletons
- The space is irreducible
-/

/-- The generic point is in every nonempty open set. -/
theorem genericPoint_mem_of_nonempty_open {U : Set (CurvePoint C)}
    (hU : isZariskiOpen C U) (hne : U.Nonempty) :
    genericPoint C ∈ U := by
  rcases hU with rfl | ⟨hgen, _⟩
  · exact absurd rfl (Set.nonempty_iff_ne_empty.mp hne)
  · exact hgen

/-- The closure of the generic point is the whole space (using Zariski topology). -/
theorem closure_genericPoint_eq_univ :
    @closure (CurvePoint C) (zariskiTopology C) {genericPoint C} = Set.univ := by
  ext x
  simp only [Set.mem_univ, iff_true]
  rw [@mem_closure_iff (CurvePoint C) (zariskiTopology C)]
  intro U hU hx_mem
  -- U is open and contains x, need to show U ∩ {genericPoint C} is nonempty
  have hne : U.Nonempty := ⟨x, hx_mem⟩
  have hgen_in_U := genericPoint_mem_of_nonempty_open C hU hne
  exact ⟨genericPoint C, hgen_in_U, rfl⟩

/-- The generic point is dense in the Zariski topology. -/
theorem genericPoint_dense :
    @Dense (CurvePoint C) (zariskiTopology C) {genericPoint C} := by
  rw [@dense_iff_closure_eq (CurvePoint C) (zariskiTopology C)]
  exact closure_genericPoint_eq_univ C

/-- Each closed point {p} is a closed set in the Zariski topology. -/
theorem closedPoint_isClosed (p : C.Point) :
    @IsClosed (CurvePoint C) (zariskiTopology C) {closedPoint C p} := by
  -- IsClosed s ↔ IsOpen sᶜ
  -- We need to show {closedPoint C p}ᶜ is Zariski-open
  have hopen : (zariskiTopology C).IsOpen {closedPoint C p}ᶜ := by
    show isZariskiOpen C {closedPoint C p}ᶜ
    right
    constructor
    · -- genericPoint ∈ {closedPoint C p}ᶜ
      simp only [Set.mem_compl_iff, Set.mem_singleton_iff, genericPoint, closedPoint]
      exact (Option.some_ne_none p).symm
    · -- {closedPoint C p}ᶜᶜ is finite
      simp only [compl_compl]
      exact Set.finite_singleton _
  -- IsClosed is defined as IsOpen of complement
  exact @IsClosed.mk (CurvePoint C) (zariskiTopology C) {closedPoint C p} hopen

/-- The space is irreducible: any two nonempty opens intersect. -/
theorem curveSpace_isPreirreducible :
    @IsPreirreducible (CurvePoint C) (zariskiTopology C) Set.univ := by
  -- IsPreirreducible s means: for all U V open, (s ∩ U).Nonempty → (s ∩ V).Nonempty → (s ∩ (U ∩ V)).Nonempty
  intro U V hU_open hV_open hU_inter_ne hV_inter_ne
  simp only [Set.univ_inter] at hU_inter_ne hV_inter_ne ⊢
  -- Now hU_inter_ne : U.Nonempty, hV_inter_ne : V.Nonempty
  -- The generic point is in both U and V (since they're nonempty opens)
  have hgen_U := genericPoint_mem_of_nonempty_open C hU_open hU_inter_ne
  have hgen_V := genericPoint_mem_of_nonempty_open C hV_open hV_inter_ne
  exact ⟨genericPoint C, hgen_U, hgen_V⟩

/-- The space is irreducible. -/
theorem curveSpace_irreducible :
    @IsIrreducible (CurvePoint C) (zariskiTopology C) Set.univ :=
  ⟨⟨genericPoint C, trivial⟩, curveSpace_isPreirreducible C⟩

/-!
## DVR Structure at Closed Points

The valuation ring at a closed point p is a discrete valuation ring.
Key properties:
- It's a domain (subring of a field)
- It has a unique maximal ideal
- The maximal ideal is principal (generated by local parameter)
-/

/-- The valuation ring at p is nontrivial (0 ≠ 1). -/
instance valuationSubringAt_nontrivial (p : C.Point) :
    Nontrivial (ValuationSubringAt C p) :=
  ⟨⟨0, 1, fun h => zero_ne_one (congrArg Subtype.val h)⟩⟩

/-- The valuation ring at p has no zero divisors (it's a subring of a field). -/
instance valuationSubringAt_noZeroDivisors (p : C.Point) :
    NoZeroDivisors (ValuationSubringAt C p) where
  eq_zero_or_eq_zero_of_mul_eq_zero {a b} hab := by
    have hab' : a.val * b.val = 0 := congrArg Subtype.val hab
    rcases mul_eq_zero.mp hab' with ha | hb
    · left; exact Subtype.ext ha
    · right; exact Subtype.ext hb

/-- The valuation ring at p is a domain (it's a subring of a field). -/
instance valuationSubringAt_isDomain (p : C.Point) :
    IsDomain (ValuationSubringAt C p) := {}

/-- The maximal ideal at p consists of elements with positive valuation. -/
def maximalIdealSubset (p : C.Point) : Set (ValuationSubringAt C p) :=
  {f | 0 < C.toAlgebraicCurve.valuation p f.val}

/-- Elements not in the maximal ideal have valuation zero. -/
theorem valuation_zero_of_not_mem_maximalIdeal (p : C.Point) (f : ValuationSubringAt C p)
    (hf : f ∉ maximalIdealSubset C p) :
    C.toAlgebraicCurve.valuation p f.val = 0 := by
  simp only [maximalIdealSubset, Set.mem_setOf_eq, not_lt] at hf
  have hf_mem : 0 ≤ C.toAlgebraicCurve.valuation p f.val :=
    (mem_valuationSubringAt C p f.val).mp f.property
  omega

/-- Elements not in the maximal ideal are units in the valuation ring. -/
theorem isUnit_of_not_mem_maximalIdeal (p : C.Point) (f : ValuationSubringAt C p)
    (hf : f ∉ maximalIdealSubset C p) (hf_ne : f ≠ 0) :
    IsUnit f := by
  have hf_val_eq := valuation_zero_of_not_mem_maximalIdeal C p f hf
  -- f⁻¹ (in function field) is also in the valuation ring
  have hf_ne' : f.val ≠ 0 := fun h => hf_ne (Subtype.ext h)
  have hinv_val : C.toAlgebraicCurve.valuation p f.val⁻¹ = 0 := by
    rw [C.toAlgebraicCurve.valuation_inv p f.val hf_ne', hf_val_eq]
    ring
  have hinv_mem : f.val⁻¹ ∈ ValuationSubringAt C p := by
    simp only [mem_valuationSubringAt, hinv_val]; exact le_refl 0
  -- Construct the unit
  refine ⟨⟨f, ⟨f.val⁻¹, hinv_mem⟩, ?_, ?_⟩, rfl⟩
  · ext; simp only [Subring.coe_mul, Subring.coe_one]; exact mul_inv_cancel₀ hf_ne'
  · ext; simp only [Subring.coe_mul, Subring.coe_one]; exact inv_mul_cancel₀ hf_ne'

/-- The local parameter at p is in the valuation ring. -/
theorem localParameter_mem_valuationSubring (p : C.Point) :
    C.localParameter p ∈ ValuationSubringAt C p := by
  simp only [mem_valuationSubringAt, C.localParameter_valuation]
  omega

/-- The local parameter is in the maximal ideal. -/
theorem localParameter_mem_maximalIdeal (p : C.Point) :
    (⟨C.localParameter p, localParameter_mem_valuationSubring C p⟩ : ValuationSubringAt C p) ∈
      maximalIdealSubset C p := by
  simp only [maximalIdealSubset, Set.mem_setOf_eq, C.localParameter_valuation]
  omega

/-!
## Properness via Valuative Criterion

The `regularIsConstant` axiom in `CompactAlgebraicCurve` is essentially the
valuative criterion of properness: a function regular everywhere (v_p(f) ≥ 0
for all p) must be constant.

This is a key property that distinguishes proper curves from affine curves.
-/

/-- A function in all valuation rings is constant.
    This is the algebraic form of the valuative criterion. -/
theorem regular_everywhere_isConstant (f : C.FunctionField)
    (hf : ∀ p : C.Point, f ∈ ValuationSubringAt C p) :
    ∃ c : ℂ, f = @algebraMap ℂ C.FunctionField _ _ C.algebraInst.algebraInst c := by
  have hreg : ∀ p : C.Point, 0 ≤ C.toAlgebraicCurve.valuation p f := fun p =>
    (mem_valuationSubringAt C p f).mp (hf p)
  exact C.regularIsConstant f hreg

/-!
## Summary

This file establishes key scheme-theoretic properties:

1. **Irreducibility**: The curve space is irreducible with dense generic point
2. **Closed points are closed**: Each singleton {p} is a closed set
3. **Local rings are domains**: The valuation rings are integral domains
4. **Units characterization**: Elements with valuation 0 are units
5. **Properness**: Regular functions everywhere are constant

These properties, combined with SpectrumConstruction.lean, establish that the
curve from CompactAlgebraicCurve has the structure of a smooth proper curve scheme.
-/

end RiemannSurfaces.GAGA.Bridge
